/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapaSalasRouteImport } from './routes/mapa-salas'
import { Route as MinhasTurmasRouteImport } from './routes/minhas-turmas'
import { Route as NovoChamadoRouteImport } from './routes/novo-chamado'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as UnidadesRouteImport } from './routes/unidades'
import { Route as UsuariosRouteImport } from './routes/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaSalasRoute = MapaSalasRouteImport.update({
  id: '/mapa-salas',
  path: '/mapa-salas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasTurmasRoute = MinhasTurmasRouteImport.update({
  id: '/minhas-turmas',
  path: '/minhas-turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoChamadoRoute = NovoChamadoRouteImport.update({
  id: '/novo-chamado',
  path: '/novo-chamado',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadesRoute = UnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chamados': typeof ChamadosRoute
  '/dashboard': typeof DashboardRoute
  '/equipamentos': typeof EquipamentosRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mapa-salas': typeof MapaSalasRoute
  '/minhas-turmas': typeof MinhasTurmasRoute
  '/novo-chamado': typeof NovoChamadoRoute
  '/relatorios': typeof RelatoriosRoute
  '/unidades': typeof UnidadesRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chamados': typeof ChamadosRoute
  '/dashboard': typeof DashboardRoute
  '/equipamentos': typeof EquipamentosRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mapa-salas': typeof MapaSalasRoute
  '/minhas-turmas': typeof MinhasTurmasRoute
  '/novo-chamado': typeof NovoChamadoRoute
  '/relatorios': typeof RelatoriosRoute
  '/unidades': typeof UnidadesRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chamados': typeof ChamadosRoute
  '/dashboard': typeof DashboardRoute
  '/equipamentos': typeof EquipamentosRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mapa-salas': typeof MapaSalasRoute
  '/minhas-turmas': typeof MinhasTurmasRoute
  '/novo-chamado': typeof NovoChamadoRoute
  '/relatorios': typeof RelatoriosRoute
  '/unidades': typeof UnidadesRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chamados'
    | '/dashboard'
    | '/equipamentos'
    | '/home'
    | '/login'
    | '/mapa-salas'
    | '/minhas-turmas'
    | '/novo-chamado'
    | '/relatorios'
    | '/unidades'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chamados'
    | '/dashboard'
    | '/equipamentos'
    | '/home'
    | '/login'
    | '/mapa-salas'
    | '/minhas-turmas'
    | '/novo-chamado'
    | '/relatorios'
    | '/unidades'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chamados'
    | '/dashboard'
    | '/equipamentos'
    | '/home'
    | '/login'
    | '/mapa-salas'
    | '/minhas-turmas'
    | '/novo-chamado'
    | '/relatorios'
    | '/unidades'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChamadosRoute: typeof ChamadosRoute
  DashboardRoute: typeof DashboardRoute
  EquipamentosRoute: typeof EquipamentosRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MapaSalasRoute: typeof MapaSalasRoute
  MinhasTurmasRoute: typeof MinhasTurmasRoute
  NovoChamadoRoute: typeof NovoChamadoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  UnidadesRoute: typeof UnidadesRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-salas': {
      id: '/mapa-salas'
      path: '/mapa-salas'
      fullPath: '/mapa-salas'
      preLoaderRoute: typeof MapaSalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-turmas': {
      id: '/minhas-turmas'
      path: '/minhas-turmas'
      fullPath: '/minhas-turmas'
      preLoaderRoute: typeof MinhasTurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-chamado': {
      id: '/novo-chamado'
      path: '/novo-chamado'
      fullPath: '/novo-chamado'
      preLoaderRoute: typeof NovoChamadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades': {
      id: '/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof UnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChamadosRoute: ChamadosRoute,
  DashboardRoute: DashboardRoute,
  EquipamentosRoute: EquipamentosRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MapaSalasRoute: MapaSalasRoute,
  MinhasTurmasRoute: MinhasTurmasRoute,
  NovoChamadoRoute: NovoChamadoRoute,
  RelatoriosRoute: RelatoriosRoute,
  UnidadesRoute: UnidadesRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
